set the default column names for some cases
turbot/steampipe-plugin-csv pull request #42
Opened 2022-10-06 10:58 UTC by daeho-ro

If there is no header row, you may want to use the default column names. Of course it is not easy to judge that but, at least we know that there is the case.

1. header row has the empty value
2. header row has the duplicated value

You could add more cases but I am only dealing with those two cases.
I have tested `golangci-lint` at local.

# Example query results
<details>
  <summary>Results</summary>

1.  When header row has the duplicated value,

```
> cat test.csv
a,,b,b,c
1,1,1,1,1
2,2,2,2,2
3,3,3,3,3
4,4,4,4,4
```

the query result is given as follows:
```
> select * from test
+-----+-----+-----+-----+-----+---------------------------+
| _c0 | _c1 | _c2 | _c3 | _c4 | _ctx                      |
+-----+-----+-----+-----+-----+---------------------------+
| 2   | 2   | 2   | 2   | 2   | {"connection_name":"csv"} |
| 4   | 4   | 4   | 4   | 4   | {"connection_name":"csv"} |
| a   |     | b   | b   | c   | {"connection_name":"csv"} |
| 1   | 1   | 1   | 1   | 1   | {"connection_name":"csv"} |
| 3   | 3   | 3   | 3   | 3   | {"connection_name":"csv"} |
+-----+-----+-----+-----+-----+---------------------------+
```

3. When header row has the duplicated value,

```
> cat test.csv
a,a,b,b,c
1,1,1,1,1
2,2,2,2,2
3,3,3,3,3
4,4,4,4,4
```

the query result is given as follows:
```
> select * from test
+-----+-----+-----+-----+-----+---------------------------+
| _c0 | _c1 | _c2 | _c3 | _c4 | _ctx                      |
+-----+-----+-----+-----+-----+---------------------------+
| 3   | 3   | 3   | 3   | 3   | {"connection_name":"csv"} |
| a   | a   | b   | b   | c   | {"connection_name":"csv"} |
| 1   | 1   | 1   | 1   | 1   | {"connection_name":"csv"} |
| 2   | 2   | 2   | 2   | 2   | {"connection_name":"csv"} |
| 4   | 4   | 4   | 4   | 4   | {"connection_name":"csv"} |
+-----+-----+-----+-----+-----+---------------------------+
```
</details>

2022-10-07 01:43 UTC, daeho-ro commented
During the setting the header names, I can handle the BOM bytes which causes an error for the issue #36 and #38.
When I set the headers, simply remove the prefix unicode `\uFEFF` for the first header and that is it.

Here is what I tested. I prepare the file which has the BOM bytes, you can see that the first 3 bytes `efbbbf` indicate BOM.
```
xxd test2.csv
00000000: efbb bf61 2c62 2c63 0d0a 622c 322c eb82  ...a,b,c..b,2,..
00000010: 980d 0a63 2c33 2ceb 8ba4 0d0a 642c 342c  ...c,3,.....d,4,
00000020: eb9d bc0d 0a65 2c35 2ceb a788 0d0a 662c  .....e,5,.....f,
00000030: 362c ebb0 940d 0a67 2c37 2cec 82ac 0d0a  6,.....g,7,.....
```
Then, query makes a table but still with the BOM bytes!
```
> .inspect test2
+--------+-------+-------------------------------------------------------+
| column | type  | description                                           |
+--------+-------+-------------------------------------------------------+
| _ctx   | jsonb | Steampipe context in JSON form, e.g. connection_name. |
| b      | text  | Field 1.                                              |
| c      | text  | Field 2.                                              |
| ﻿a      | text  | Field 0.                                              |
+--------+-------+-------------------------------------------------------+
```
Column order should be `a`, `b`, and `c` but the `a` has the BOM bytes and so it has the hidden character, mix the order.

After I add the removing process, 
```
> .inspect test2
+--------+-------+-------------------------------------------------------+
| column | type  | description                                           |
+--------+-------+-------------------------------------------------------+
| _ctx   | jsonb | Steampipe context in JSON form, e.g. connection_name. |
| a      | text  | Field 0.                                              |
| b      | text  | Field 1.                                              |
| c      | text  | Field 2.                                              |
+--------+-------+-------------------------------------------------------+
```
 The column order is fixed and can query for the column `a`.

```
> select a from test2
+---+
| a |
+---+
| b |
| g |
| d |
| f |
| e |
| c |
+---+
```

2022-10-07 02:20 UTC, e-gineer commented
I merged a commit an hour ago to skip BOM bytes ... sorry, I didn't realize you were working on it ... might be worth checking that out to combine with your header work here - commit ba897d3f03d2bad06770699e76f81812a4133b93

2022-10-07 02:26 UTC, daeho-ro commented
@e-gineer Oh, I even don't know about that!
I will merge your code and update pr soon!
Then I can remove my BOM updates.

2022-10-07 04:01 UTC, daeho-ro commented
I reset my code base to the most recent commit, and remain only codes for the default column name setting.

2022-10-07 15:28 UTC, cbruno10 commented
@daeho-ro This is an interesting case, as right now the CSV plugin is designed to fail when an invalid header row is passed, e.g., not all values are defined, duplicate header values. Our original thinking was that in order for the plugin to create tables with proper column names, we'd require a header row.

However, according to [RFC 4180](https://www.rfc-editor.org/rfc/rfc4180):
> There maybe an optional header line appearing as the first line
       of the file with the same format as normal record lines.  This
       header will contain names corresponding to the fields in the file
       and should contain the same number of fields as the records in
       the rest of the file (the presence or absence of the header line
       should be indicated via the optional "header" parameter of this
       MIME type).
       
So if we follow RFC 4180, the header could be optional, and the plugin could use the logic from this PR:
- Try to parse the first row as the header row
- If there are no missing values and no duplicate values, assume it's a valid header and use it to create column names
- Else, assume there is no header row, and use generic column names

For column names, I think I'd avoid starting them with `_`, as this is reserved for Steampipe columns like `_ctx`, so column names could end up being c0, c1, c2, etc.

Alternatively, we could follow what we do in the Google Sheets plugin, which uses the following conventions as per [Table Restrictions and Notes](https://hub.steampipe.io/plugins/turbot/googlesheets/tables/%7Bsheet_name%7D#table-restrictions-and-notes):
- CSV tables will only be created for sheets that have data in cell A1.
- If a sheet's header row is missing some values, the table will use the column index for the column name.
- If a sheet's header row has more than one column with same name, column indexes will be appended onto the end of duplicate columns.
- If a sheet's header row has vertically merged cells, the table will use the merged cell's value for all affected cells and apply duplicate protection.

The first and last items don't apply to this table, but we could take alternatively take the same approach in this plugin, but use numbers instead of letters throughout the column names.

@daeho-ro Please let me know if you have any thoughts on the alternative approach I outlined above (or about anything else I mentioned).

@johnsmyth I'd also be interested in if you have any thoughts on this topic, thanks!

2022-10-08 00:55 UTC, daeho-ro commented
If the header is present and corrupted, it looks good if it was handled by Google Sheets. But there are many cases where the header is missing, and I'm thinking about this case. In this case, the first row is just a row of data and should not be modified. So I want to add a default header to save the first row in case the header is malformed. In order to prevent data tampering, I rule out the case of modifying the header and this is the reason why I'd like to add the default header.

2022-10-08 02:20 UTC, daeho-ro commented
I think it is possible to give an option and then user can select the behavior how the plugin set the header. Maybe header option with the values always true or false and auto.

2022-10-10 02:31 UTC, daeho-ro commented
I turn this pr to draft because it could conflict with the prior pr #41.

There are a lot of changes of my code and the aim is to keep the original behavior. To use the updated header feature, user should turn the option to "auto" and it will change the header only if the header has the empty value or duplicated value. When it can be thought as the standard, you can change it to be the default behavior later.

I have made another changes that is for the errors. Until now, when you met the error in the `tableCSV`, it is hard to find which CSV files are bad because the plugin only shows the error for a CSV. So, I collect the errors into a slice, and raise the error later which makes you can find all the errors from the log file. Of course, the steampipe CLI can only give an error but I want to add the logs for all bad CSV files.

2022-10-28 21:22 UTC, cbruno10 requested changes
@daeho-ro Thanks again for raising this PR! I've added a fairly lengthy suggestion/proposal, so please have a look when you get a chance and let me know your thoughts, as I believe this PR is directionally correct and will make the plugin easier to use.

2022-10-28 21:22 UTC, cbruno10 commented on config/csv.spc
> +  header = "on"
Some of this proposal's design was taken from how we handle possible header rows in the [Google Sheets dynamic sheet table](https://hub.steampipe.io/plugins/turbot/googlesheets/tables/%7Bsheet_name%7D), with a lot of the table name resolution code in https://github.com/turbot/steampipe-plugin-googlesheets/blob/4676e23c1b5894c6a17f6ff718c594a6c6071397/googlesheets/plugin.go#L32.

2022-10-30 07:13 UTC, daeho-ro commented on config/csv.spc
> +  header = "on"
In this PR, I want to add the logic that automatically judge the first row is a CSV header row or not. I think what you are talking about is how to recover the header row when the first row is the CSV header.

I am not focusing on the healing of the header column names, but  just want to determine whether the first row is a header row or not, automatically. This case is not covered by 2 cases, use_headers equals true or false. This is the reason why I added the auto case. Based on my experience,  I guess the first row is mostly not a header row when the first row has the duplicated or empty value and so I added the header row by my self.

2022-10-30 15:42 UTC, cbruno10 commented on config/csv.spc
> +  header = "on"
@daeho-ro Ah ok, sorry, I think I misunderstood what you were trying to do initially. So if I understand correctly now, when the `header` config arg is set to:
- `on`: Always try and create a header row from the first row, if there are any duplicate values or missing values, error and stop trying to load the files (current behaviour).
- `off`: Always use the generic column names, e.g., `c1`, `c2`, `c3`, even if the first row could be a header row
- `auto`: Check the first row of each file. If there are no duplicate or missing values, use that as the header row; else, use the generic column names for that file.

Is my understanding above correct?

2022-10-31 00:10 UTC, daeho-ro commented on config/csv.spc
> +  header = "on"
@cbruno10 That is right. We are talking about how we can handle the duplicated or empty header values. Those modifications are conflict each other, so we can add more option, e.g. header handling strategy `header_strategy = modify` or `add` and it can be only work with `header = on`. Then we can use this option to handle the case of duplicated or empty headers.

After this change, `header` config will have only two values `on` and `off`, thus I can apply your suggestion to change the name of the option and values. And there is another option `header_strategy` with the values `add` and `modify`. Modify means the first row is assumed as the header and if there is an error like duplicated or empty then modify the header name such as your suggestion. Add means not modify the first row but add the header row by default and dealing the first row as data. 

How do you think about this?

2022-10-31 01:05 UTC, cbruno10 commented on config/csv.spc
> +  header = "on"
@daeho-ro Now that I understand more, I like the idea of having 1 config arg with 3 values (just like you described), which gives users the flexibility on how they want to use the CSV plugin. I'm going to try out your branch more tomorrow and see how it handles some of my current CSVs, but overall I'm in favor of what you're proposing in this PR.

I'll add any other questions/suggestions I have tomorrow after trying out your PR more!

2022-10-31 23:51 UTC, cbruno10 approved these changes

2022-10-31 23:52 UTC, merged

2022-10-31 23:53 UTC, cbruno10 commented
Thanks for the ideas and implementation, @daeho-ro, we really appreciate all of the thought and work you put into this PR!